swagger: '2.0'

info:
  description: |
    PJMS API
  version: 1.0.0
  title: PJMS

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

paths:
  /image:
    post:
      tags:
        - image
      parameters:
        - in: body
          name: image
          required: true

      responses:
        201:
          description: Created

        401:
          description: Unauthorized
        422:
          description: Unprocessable Entity

        500:
          description: Internal Server Error

  /customer/login:
    post:
      tags:
        - customer
      parameters:
        - in: body
          name: customer
          required: true

      responses:
        200:
          description: OK

        401:
          description: Unauthorized
        404:
          description: Not Found
        422:
          description: Unprocessable Entity

        500:
          description: Internal Server Error

  /member:
    post:
      tags:
        - customer
      parameters:
        - in: body
          name: customer
          required: true

      responses:
        201:
          description: Created

        401:
          description: Unauthorized
        500:
          description: Internal Server Error

  /member/{id}:
    put:
      tags:
        - customer
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          type: 'integer'
          format: 'int64'
        - in: body
          name: customer
          required: true

      responses:
        200:
          description: OK

        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error

  /token:
    post:
      tags:
        - token
      parameters:
        - in: body
          name: customer
          required: true

      responses:
        200:
          description: OK

        401:
          description: Unauthorized
        404:
          description: Not Found
        422:
          description: Unprocessable Entity

        500:
          description: Internal Server Error
